### ISSUE TITLE
Enumとswetch-case文について

### ISSUE THREAD

**Issue by ghost** [naoki-takashio/rakus-schedule#14]
たかしーへ

``` enum
public enum EnumStatus {
    STAND_BY(1),
    WORKING(2),
    IN_REVIEW(3)
    DONE(4);

    private final int id;

    private MyEnum(final int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }
}
```

``` switch-case
switch (task.getTaskStatus()) {
    case EnumStatus.STAND_BY.getId():
        standByTaskList.add(task);
        break;
    case EnumStatus.WORKING.getId():
        WorkingTaskList.add(task);
        break;
    case EnumStatus.IN_REVIEW.getId():
        inReviewTaskList.add(task);
        break;
    case EnumStatus.DONE.getId():
        SoneTaskList.add(task);
        break;
    default:
        throw new HogeException(e)
}
```

的な感じですかね？
Rubyがcaseとenumable系の相性が良いみたいだから提案してみたけどどうでしょう。
自分は予想より冗長だったw

下記、参考のページを読み込めばもっと綺麗に書けそう。
利点は数字がどのステータスを表すか一目でわかるところ。

そもそも`private final Integer STAND_BY_STATUS = 1`とか定数にするのが正解だったかもw

参考：
Enum で振る舞う
http://qiita.com/KeithYokoma/items/9681b130ea132cfad64d
7ステップで理解するJavaでの列挙型／enum使用法
http://www.atmarkit.co.jp/ait/articles/1103/03/news107.html

**Comment by ghost** [comment]
あ、このページをJava詳しい人に見せて意見伺えたりするなら嬉しい。
おそらく書き方自体も間違ってる気がする。

**Comment by nayuta28** [comment]
これなら定数宣言にしちゃったほうが冗長にならないしいいかも。
もう一個の案としては、task_statusをString型にしてenumの列挙子と比較するかな。

public enum TaskStatus {
      STAND_BY,
      WORKING,
      IN_REVIEW,
      DONE,
}

switch (task.getTaskStatus()) {
    case STAND_BY:
        standByTaskList.add(task);
        break;
    case WORKING:
        workingTaskList.add(task);
        break;
    case IN_REVIEW:
        inReviewTaskList.add(task);
        break;
    case DONE:
        doneTaskList.add(task);
        break;
    default:
        throw new HogeException(e)
}

これならまだ見やすい？

**Comment by ghost** [comment]
ここだけの見易さの為にDB構成変えるのは違う気もする。
どっかのSQLで `order by status` みたいな事しないかなぁ。

**Comment by ghost** [comment]
要求定義ってのかな？それが固まってないからなんとも。

**Comment by ghost** [comment]
```
Map<String, Integer> status = new Map<>;
status.put("standBy", 1);

(略)

case status.get("standBy"):

(略)
```

的な事やりたいお…でもこれJavaでは間違ってるんだろうなぁ…

**Comment by nayuta28** [comment]
なんか個人的にcase文にメソッドが入ってるのが好きじゃない・・・
enumは他のとこでも使うかもしれないから作るのは大賛成で、
ここではif文で
if (task.getTaskStatus() == EnumStatus.STAND_BY.getId()) {
      standByTaskList.add(task);
else if 〜

のほうが分かりやすい気がする。
多分完全に好みの問題。

**Comment by ghost** [comment]
自分もcase文はメソッドってイメージ無いんだよなぁ。
enumの使い方忘れてたから完全に見切り発車で提案してた。

**Comment by ghost** [comment]
てことで宮原くんに任せた！w

**Comment by nayuta28** [comment]
Mapのは間違ってはいないと思う！
むしろ伝わる！
ただ冗長になるだけであんま意味なくない？ってなる気がする。。。

**Comment by nayuta28** [comment]
もう宮原くんのセンスに任せるｗ

**Comment by ghost** [comment]
まあコメントがあれば万事OKだと思うw

**Comment by ghost** [comment]
再度先輩に聞いてみた。
enumはO/Rマッパーと組み合わせて使うものらしい。
プレーンなJavaとかだと面倒臭いとのこと。
定数でいいんじゃない？とのことでした。

ちな、その先輩はO/Rマッパーを使う場合statusが2種類しかなくてもenum使うとのこと。
入力できる値を制限したりきちんと定義されているのが大事だそうです。
